# Generated by Django 4.1.2 on 2023-06-05 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2023, 6, 5, 14, 13, 6, 771252, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 5, 14, 13, 6, 767190, tzinfo=datetime.timezone.utc)),
        ),
    ]
